# Generated by Django 5.2.4 on 2025-07-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Product Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('price', models.IntegerField(verbose_name='Product Price')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Product Preview Image')),
            ],
        ),
    ]
