# Generated by Django 5.2.4 on 2025-07-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='News Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='News Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='News Image')),
            ],
        ),
    ]
