# Generated by Django 5.2.4 on 2025-07-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='bonus_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Product Bonus Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='brend',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Brend'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_production',
            field=models.CharField(default=1, verbose_name='Products production country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(default=1, max_length=200, verbose_name='Product Full Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Product On Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Product Old Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Product Weight'),
        ),
    ]
